[phases.setup]
nixPkgs = ["python310", "postgresql"]
aptPkgs = ["python3-pip"]

[phases.install]
cmds = ["cd backend && python -m pip install --upgrade pip", "cd backend && python -m pip install -r requirements/production.txt"]

[phases.build]
cmds = ["cd backend && python manage.py collectstatic --noinput"]

[start]
cmd = "cd backend && python manage.py migrate && gunicorn config.wsgi:application --bind 0.0.0.0:$PORT"
